### ISSUE TITLE
Works only on Windows platform

### ISSUE THREAD

**Issue by GabLeRoux** [chenjd/Realistic-Real-Time-Grass-Rendering-With-Unity#2]
Hi, thanks for this nice project.
I'm just leaving this as a note here as I gave it a try. It's mentioned win-64 platform in the readme with a badge, but here's what happens on MacOS:

> Drawing with MeshTopology.Points, yet the vertex program 'Hidden/InternalErrorShader' does not have PSIZE output.

![image](https://user-images.githubusercontent.com/1264761/97065698-4fde5c00-157d-11eb-81ef-e8ab9a876173.png)

It seems to work fine on Windows :+1: :) Also, I did not confirm this, but I think that building with `-nographics` kind of breaks global illumination, or mayne it's because I upgraded the project from 2017.1.0f3 to 2020.1.7f1, but results looks like this on the build:

![](https://media2.giphy.com/media/0A91ZkzOaFPLQNStDI/giphy.gif)

Anyway, it's cool, thanks for sharing this project :D

**Comment by chenjd** [comment]
😃
